version: "3"
services:
  django:
    build: ./django
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - superlists-net
    volumes:
      - django-static:/app/static
      - django-db:/app/db.sqlite3
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - superlists-net
    restart: unless-stopped
    volumes:
      - django-static:/opt/app/static
networks:
  superlists-net:
volumes:
  django-static:
  django-db: