# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
